### ISSUE TITLE
Boost 1.61

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#90]
continued from #88 /cc @artemp 

`mapnik` build with `boost@1.61` errors with:

```
"c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj" (ClCompile target) (1) ->
(ClCompile target) -> 
  c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): error C2672: 'swap': no matching overloaded function found (compiling source file ..\..\src\image_filter_grammar.cpp) [c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
  c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): error C2784: 'void boost::spirit::swap(boost::spirit::multi_pass<T,Policies> &,boost::spirit::multi_pass<T,Policies> &)': could not deduce template argument for 'boost::spirit::multi_pass<T,Policies> &' from 'mapnik::color' (compiling source file ..\..\src\image_filter_grammar.cpp) [c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
```
