### ISSUE TITLE
Error building gdal/odbccp32.lib

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#53]
@BergWerkGIS - working on tagging mapnik v3.0.1 and therefore kicked off a windows build of the Mapnik SDK. Seeing this error:

```
x64|||2015-07-28 02:20:42|||stdout|||   Creating library gdal_i.lib and object gdal_i.exp
x64|||2015-07-28 02:20:42|||stdout|||odbccp32.lib(dllload.obj) : error LNK2019: unresolved external symbol _vsnwprintf_s referenced in function StringCchPrintfW
x64|||2015-07-28 02:20:42|||stdout|||gdal200.dll : fatal error LNK1120: 1 unresolved externals
x64|||2015-07-28 02:20:43|||stderr|||NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
```

Is this perhaps happening because the `legacy_stdio_definitions.lib` is still needed when building with VS 2014? I'm open to just moving to 2015, but creating this nonetheless in case the fix is quick.

**Comment by BergWerkGIS** [comment]
This error is expected with VS2014.
As I've had good results with VS2015 till now, I've already switched the scripts to VS2015.
But build server is not yet updated to VS2015.
I can manually publish the SDK as soon as it is ready.

Reopen, if you want to stay with VS2014, which I don't recommend (See latest tickets for Mapbox Studio).

**Comment by springmeyer** [comment]
> Reopen, if you want to stay with VS2014

Full steam ahead on 2015 sounds good.

**Comment by rmkemker** [comment]
I am having the same issue, but I am using VS2015.  The error message was nearly identical.  Was there ever a solution to this issue?  Thank-you.

**Comment by BergWerkGIS** [comment]
@rmkemker Not seeing any problems with `gdal 2.0.0` or `gdal 2.0.1` and VS2015.
We use [this script](https://github.com/mapbox/windows-builds/blob/master/scripts/build_gdal.bat) for building gdal.

**Comment by rmkemker** [comment]
I will give that a try.  Thank-you!

**Comment by BergWerkGIS** [comment]
@rmkemker 
A bit of information:
If the error still occurs for you and you don't need ODBC support (e.g. MS SQL Server) you can either
* turn it of in [`nmake.opt`](https://github.com/OSGeo/gdal/blob/e5f7f305dacf2d1a518c28bb2a61ebe47d2d51ea/gdal/nmake.opt#L228) or
* set the environment variable `SET ODBC_SUPPORTED=0` before calling `nmake /A /F makefile.vc`.

**Comment by rmkemker** [comment]
@BergWerkGIS, I tried that and got the same error.  

    Creating library gdal_i.lib and object gdal_i.exp
    odbccp32.lib(dllload.obj) : error LNK2019: unresolved external symbol _vsnwprintf_s referenced in function StringCchPrintfW
    gdal201.dll : fatal error LNK1120: 1 unresolved externals
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
    Stop.

**Comment by BergWerkGIS** [comment]
@rmkemker are you sure, you are on latest VS2015 RTM?
For me, this error only appeared with VS2014/VS2015 CTPs and gdal <2.0.0 only.

These are the patches I used with different gdal versions and VS CTPs:
https://github.com/mapbox/windows-builds/blob/master/patches/gdal-200-VS2015RC1.diff
https://github.com/mapbox/windows-builds/blob/master/patches/gdal-VS2014CTP4.diff
https://github.com/mapbox/windows-builds/blob/master/patches/gdal-VS2015RC1.diff

Otherwise I'm out of ideas and you might want to post to the official gdal mailing list:
http://lists.osgeo.org/mailman/listinfo/gdal-dev

**Comment by rouault** [comment]
I just fought a bit to solve the same issue and I realize you've found the solution already... Anyway... Upstreamed as https://trac.osgeo.org/gdal/changeset/32019 / https://trac.osgeo.org/gdal/ticket/6255 . There's also now an appveyor target for VS2015 : https://ci.appveyor.com/project/rouault/gdal-coverage/build/1.0.1430/job/tjitd3pen0wenc9j

**Comment by springmeyer** [comment]
Thank you for the followup @rouault!
